Addition of Via Rail and Train de Charlevoix
RailFansCanada/RailFansMap pull request #218
Opened 2022-11-03 07:01 UTC by davidbellerive

Using their respective GTFS data, added the following elements to the map:

> Via Rail Canada: alignment, stops (including flag stops), icon, main lines / sectors and maintenance centres.

> Train de Charlevoix: alignment, stops, icon.

2022-11-04 00:46 UTC, dellisd requested changes
The icons under `icons/vancouver` should be removed and put into the other PR with the other SkyTrain stuff.

For all of the VIA lines, I'd make each of their IDs `via/{name}`. This just helps group them together, and it'll also change how the icons are sorted in the station label. They're sorted alphabetically by ID so VIA would go last and I think that makes the most sense.

Also, if we could just keep the VIA lines all yellow for now. We can add colour later if we decide it makes more sense.

Lastly, there's still the `viarail.json` file which I assume is the original file with all of the data before it was split up. I don't think we'll need to keep that one.

2022-11-04 00:46 UTC, dellisd commented on src/config/config.json
> +{
This file should be deleted (it looks like a copy of the actual config?)

2022-11-04 01:50 UTC, davidbellerive commented
Changes have been implemented, copy of config file removed as it was misplaced.

2022-12-10 21:18 UTC, dellisd requested changes

2022-12-10 21:18 UTC, dellisd commented on data/viarail/montrealmaintenance.json
> +"metadata": { "id": "montrealmaintenance", "type": "rail-yard", "color": "#FFCC00", "icon": "viarail\/viarail.svg", "name": "VIA Rail Montreal Maintenance Centre", "description": "Major maintenance f
```suggestion
"metadata": { "id": "montrealmaintenance", "type": "rail-yard", "color": "#FFCC00", "icon": "viarail\/viarail.svg", "name": "VIA Rail Montreal Maintenance Centre", "description": "Major maintenance facility for VIA Rail located in Montreal.", "sources": [ "VIA Rail Canada" ], "filterKey": "via/corridor" },
```

2022-12-10 21:18 UTC, dellisd commented on data/viarail/vancouvermaintenance.json
> +"metadata": { "id": "vancouvermaintenance", "type": "rail-yard", "color": "#FFCC00", "icon": "viarail\/viarail.svg", "name": "VIA Rail Vancouver Maintenance Centre", "description": "Maintenance facil
```suggestion
"metadata": { "id": "vancouvermaintenance", "type": "rail-yard", "color": "#FFCC00", "icon": "viarail\/viarail.svg", "name": "VIA Rail Vancouver Maintenance Centre", "description": "Maintenance facility for VIA Rail located in Vancouver.", "sources": [ "VIA Rail Canada" ], "filterKey": "via/canadian" },
```

2022-12-10 21:18 UTC, dellisd commented on data/viarail/torontomaintenance.json
> +"metadata": { "id": "torontomaintenance", "type": "rail-yard", "color": "#FFCC00", "icon": "viarail\/viarail.svg", "name": "VIA Rail Toronto Maintenance Centre", "description": "Major maintenance fac
```suggestion
"metadata": { "id": "torontomaintenance", "type": "rail-yard", "color": "#FFCC00", "icon": "viarail\/viarail.svg", "name": "VIA Rail Toronto Maintenance Centre", "description": "Major maintenance facility for VIA Rail located in Toronto.", "sources": [ "VIA Rail Canada" ], "filterKey": "via/corridor" },
```

2022-12-10 21:18 UTC, dellisd commented on data/viarail/winnipegmaintenance.json
> +"metadata": { "id": "winnipegmaintenance", "type": "rail-yard", "color": "#FFCC00", "icon": "viarail\/viarail.svg", "name": "VIA Rail Winnipeg Maintenance Centre", "description": "Maintenance facilit
```suggestion
"metadata": { "id": "winnipegmaintenance", "type": "rail-yard", "color": "#FFCC00", "icon": "viarail\/viarail.svg", "name": "VIA Rail Winnipeg Maintenance Centre", "description": "Maintenance facility for VIA Rail located in Winnipeg.", "sources": [ "VIA Rail Canada" ], "filterKey": "via/canadian" },
```

2022-12-10 21:24 UTC, merged